### ISSUE TITLE
Required Learning

### ISSUE THREAD

**Issue by Gmunster33** [Gmunster33/DigiCorder#1]
# Todos...
### Complete channels tutorial, OR at least enough to confidently know:
- [x] Frontend/backend requirements for async websocket connections
- [x] Understand some of the basic *types* of consumer classes in order to properly choose one for our data stream
- [x] How to manipulate websocket connection port numbers (or if we need to worry about this)
- [x] Consumers' role in frontend control flow vs views
- [x] Decide if the consumers.py file is the proper location to pop off an async thread that `GET`s live ADSB data...

### Multithread this puppy... And use a dedicated thread to put ADSB data into our database.
- [x] Spawn exactly one thread on startup
- [x] Subscribe to a relevant API
- [x] Parse responses
- [x] Save a few for future use...
- [x] If ADSB altitude>0 and type= TEX2, send to Active_T6 table
- [x] If we get ADSB data pertaining to a currently active T6 where altitude is 0 for more than 20sec, then input/save a land time... Which triggers other fun things that currently exist :)

### Complete Django views/templates/bootstrap/UAC tutorials in order to:
- [x] Create a basic dashboard view that doesn't look like it came from the 80's
- [x] Create login screen views
- [x] Integrate dashboard view with websocket data feed
- [x] Dynamically create/destroy/recategorize html elements to include 355 buttons...
